### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by bennycode** [dimaslanjaka/hexo-post-parser#253] opened 2023-10-10 23:30 UTC
Hello, I tried to install [hexo-post-parser](https://github.com/dimaslanjaka/hexo-post-parser) because I want to use it to parse existing Markdown files into a JSON format which I can then transform into another format. Your plugin seems to be able to do this but when I try to run `npm i hexo-post-parser` it fails:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sbg-utility@1.1.5',
npm WARN EBADENGINE   required: { node: '>=14', npm: '^8', hexo: '>= 3' },
npm WARN EBADENGINE   current: { node: 'v18.18.0', npm: '9.8.1' }
npm WARN EBADENGINE }
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /home/bennycode/dev/bennycode/typescript.tv/node_modules/hexo-renderer-scss/node_modules/node-sass
npm ERR! command failed
```

Can you help me fixing the installation?

**Comment by dimaslanjaka** [comment] 2023-10-12 10:13
this package need `hexo` cuz need the `hexo.config` instance to parse markdown frontmatter post

so you need install with `npm i hexo` then `npm i hexo-post-parser`

**Comment by dimaslanjaka** [comment] 2023-10-12 10:14
> npm ERR! path /home/bennycode/dev/bennycode/typescript.tv/node_modules/hexo-renderer-scss/node_modules/node-sass
> npm ERR! command failed
> ```

look at your other package which caused failure installation

**Comment by dimaslanjaka** [comment] 2023-10-12 10:20
oh found the error. you can force installation with `npm i -f hexo-post-parser`, this caused by **npm module resolution** but no fails on parser

![image](https://github.com/dimaslanjaka/hexo-post-parser/assets/12471057/93454bc3-3423-4e73-99ff-28364a5bd068)

**Comment by dimaslanjaka** [comment] 2023-10-12 10:28
fixed in v1.2.12

**Closed by dimaslanjaka** 2023-10-12 10:28 UTC
Labels: bug

**Comment by bennycode** [comment] 2023-10-12 10:42
Thank you! I justed tested it in a new project and it works. 👍

**Comment by dimaslanjaka** [comment] 2023-10-15 23:04
might you interested to contribute [hexo+webpack+react](https://github.com/dimaslanjaka/hexo-webpack)

**Comment by bennycode** [comment] 2023-10-16 08:12
Thanks for the proposal but I am currently migrating my Hexo blog to Astro.
